version: '3.8'
services:
  single-cell:
    restart: always
    env_file: .env
    volumes:
      - ./airflow/logs:/opt/bitnami/airflow/logs
      - ./airflow/dags:/opt/bitnami/airflow/dags
      - ./data:/opt/bitnami/data
      - ./:/opt/bitnami/projects/app
    build: .
    ports:
      - 5005:5005
    networks:
      - db_network
      - web_network

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
