name: cellxgene-gateway
channels:
- bioconda
- conda-forge
dependencies:
- python=3
- requests
- psutil
- black
- twine
- isort
- coverage
- fsspec
- s3fs
- ipython
- supervisor
- leidenalg
- pyarrow
- numpy
- jupyter-book
# - scikit-learn=0.24.1
# - scipy=1.6.0
# - tiledb=0.7.7
# keep this as 1.6.1 will need to update some api calls to update version
- scanpy=1.6.1
- pip
- pip:
  - colorlog
  - dash
  - gunicorn
  - pre_commit
  - flask-appbuilder
  - dash-bootstrap-components
  - Authlib
  - cellxgene>=0.15
  - fab-coreui-theme
  - gunicorn==20.1.0
  - markupsafe==2.0.1
  - dash-bootstrap-components[pandas]
  - sphinxcontrib.datatemplates
